### ISSUE TITLE
Potential surface distance calculation improvements

### ISSUE THREAD

**Issue by rmarkello** [murraylab/brainsmash#1]
Hey `brainsmash` developers! Thanks for an exciting toolbox :raised_hands: Looking forward to using it in some of my work. I had a few thoughts after taking a closer look at the docs + code that might (hopefully) be helpful!

## Description

Calculation of surface distances using `brainsmash.workbench.cortex()` currently takes ~2 hours for a 32k vertex surface, using sub-calls to `wb_command -surface-geodesic-distance`. One of the benefits of the current method is that the vertex-to-vertex distance matrix is never stored in memory (which is great!). While ~2 hours isn't unreasonable for a one-time computation, it can be a bit annoying if you're iterating quickly over different surface projections or trying to debug something in a pipeline. There might be ways to reduce the disk I/O load of using `wb_command` and avoid storing the distance matrix in memory.

Moreover, `wb_command` doesn't (easily) allow you to disallow travel along the medial wall of surface distances along the medial wall. It seems relatively minor, but paths from e.g., the cingulum to the entorhinal cortex shouldn't be allowed to go through the medial wall, so calculation without this constraint will categorically underestimate "real" surface distances in the brain.

## Proposed solution

Using a surface file it's possible to construct a sparse graph representation (very low RAM usage) and use Dijkstra's algorithm to calculate surface distances that come _very_ close to those calculated by `wb_command`. 

The primary benefits of this in-memory calculation are that (1) it's much faster than the sub-calls to `wb_command` (~10 min for the same 32k surface—less if you parallelize), and (2) it's trivial to zero-out edges that involve vertices along the medial wall (if the user supplies a file specifying which vertices belong to the medial wall) to generate more accurate surface distances (N.B., It's still possible to do the "in-memory" computations without ever storing the whole distance matrix in memory and just saving the output text file line-by-line!)

I've got some code that takes a whack at this that I'd be happy to try and fit into the `brainsmash.workbench` submodule. I think it should be possible to provide speed-ups to both the `cortex()` and `parcellate()` functions and, ideally, allow users to provide a medial wall label file to generate more accurate surface distances.

Let me know if this is something you think would be helpful for `brainsmash`!

**Comment by jbburt** [comment]
This is absolutely something which would be helpful! This sounds like it could be encapsulated in a function which would replace what is currently brainsmash.workbench.geo._geodesic(). It could take as input a surface file, an output filename, and optionally a mask file. Thoughts? It's still unclear to me how this would apply to the parcellate() function...

**Comment by rmarkello** [comment]
The primary reason the `parcellate()` function takes ~30 min is that you have to read through the (very large) text file that gets generated with `cortex()`. So while you can speed up `cortex()`, you're still gonna hit an I/O bottleneck for `parcellate()`. If you add an additional parameter to the `cortex()` function where users can provide a label file, you can avoid the I/O issue and just reduce the vertex-vertex matrix into a parcel-parcel matrix in-memory (again, without ever storing the full vertex-vertex matrix in-memory). 

Notably, that would modify the API that you've currently created a bit, so I totally understand if you don't want to do that! Here's the doc-string of the function I was imagining, though. I've been using a modified version in my own analyses (though I skip writing to disk, generally):

```python
def get_surface_distance(surf, outfile, dlabel=None, medial=None, use_wb=False, 
                         n_proc=1, verbose=False):
    """
    Calculates surface distance for vertices in `surf` and saves to `outfile`

    Parameters
    ----------
    surf : str or os.PathLike
        Path to surface file on which to calculate distance
    outfile : str or os.PathLike
        Path to which generated distance matrix should be saved
    dlabel : str or os.PathLike, optional
        Path to file with parcel labels for provided `surf`. If provided will
        calculate parcel-parcel distances instead of vertex distances. Default:
        None
    medial : str or os.PathLike, optional
        Path to file containing labels for vertices corresponding to medial
        wall. If provided (and `use_wb=False`), will disallow calculation of
        surface distance along the medial wall. Default: None
    use_wb : bool, optional
        Whether to use calls to `wb_command -surface-geodesic-distance` for
        computation of the distance matrix; this will involve significant disk
        I/O. If False, all computations will be done in memory using the
        `scipy.sparse.csgraph.dijkstra` function. Default: False
    n_proc : int, optional
        Number of processors to use for parallelizing distance calculation. If
        negative, will use max available processors plus 1 minus the specified
        number. Default: 1 (no parallelization)
    verbose : bool, optional
        Whether to print status updates while distances are calculated.
        Default: True

    Returns
    -------
    outfile : str
        Filepath to generated distance matrix
    """
```

**Comment by jbburt** [comment]
My only concern is that I'd like the parcellate() function to be exposed to both cortex() and subcortex(). I don't know what your code internals look like, but would it be easy/possible to modularize the parcellation component? 

Also, do you think that in general we need two separate inputs for dlabel and medial? I typically use parcellation files which assign a default value, usually 0, to vertices which are not assigned to any parcel, e.g. the medial wall. I'm not sure how standard or generalizable this is though.

**Comment by rmarkello** [comment]
Gotcha! The current implementation isn't modularized such that it could readily incorporate  the current form of `subcortex()`, so I'll leave that alone for now :+1: 

Re `dlabel` and `medial`: my rationale was that if you wanted the un-parcellated vertex-vertex distance matrix (disallowing travel along the medial wall) you would just provide the `medial` file and leave `dlabel` blank. But that's not necessary if we're going to strip the `dlabel` bit out and leave all that up to the `parcellate` function! I'll go back to your `mask` parameter suggestion, for now.

(You're right, though, that most parcellation files assign 0 to the medial wall—there are some FreeSurfer label files that assign both 0 and 4 ['unknown' and 'corpuscallosum' in FreeSurfer lingo] but you don't need to support those cases if you don't want).

Either way, why don't I open up a PR so you can take a look at some of the internals since it sounds like this might be useful in _some_ form or another! It tends to be easier to discuss implementation with actual codebits to look at.

**Comment by jbburt** [comment]
I suppose I could just merge the current parcellate function with the subcortex function? And then the parcellate implementations for subcortex/cortex would just be different, which is fine. It might actually be more computationally efficient to parcellate subcortex inside the main routine anyways. I don't mind either way, so just open a PR with whatever you've got!
