### ISSUE TITLE
Implementation for generic nifti files?

### ISSUE THREAD

**Issue by gdevenyi** [murraylab/brainsmash#10]
This is a very cool tool, but I find right now a bit limiting to be restricted to HCP-style file formats and no example with plain NIFTI files.

I'd like to request an example be added for the generic case, so maps from other tools (and for other model organisms) can also benefit from this tool. Thanks!

**Comment by JianxunRen** [comment]
Same question! The cifti style is not friendly enough for most users.

**Comment by jbburt** [comment]
BrainSMASH now includes a utility for computing the Euclidean distance matrix between voxel coordinates, which I hope is sufficiently general. Documentation for the new implementation can be found here: https://brainsmash.readthedocs.io/en/latest/example.html#whole-brain-volume

Please let me know if this addresses your needs or if there is other specific functionality which you have in mind. Thanks!

**Comment by gdevenyi** [comment]
Thanks @jbburt 

One clarification
> A text file containing voxel coordinates (with shape N rows by 3 columns)

What format? CSV, tab separated, space separated?

**Comment by jbburt** [comment]
@gdevenyi whitespace-separated is what I had in mind -- if this is problematic I could make the implementation more general!
