### ISSUE TITLE
Support of Spearman rank correlation?

### ISSUE THREAD

**Issue by YaoMeng94** [murraylab/brainsmash#16]
Hi Joshua,
    I've been using BrainSmash quite lot recent, it's a great tool for brain map correlation analysis, helps a lot! But I noticed it seems do not support Spearman correlation which should be a quite high rank need for us, is there something I missed or will you consider to add Spearman support to BrainSmash

**Comment by jbburt** [comment]
Hello, 

I'm afraid I don't understand your question. BrainSMASH does not perform analyses of surrogate brain maps, it simply generates them for you to analyze at your discretion. Could you please elaborate?

**Comment by YaoMeng94** [comment]
Simply, the doc file of BrainSMASH shows how to compute Pearson correlation between one brain feature map and surrogate maps (by mapgen.stats), can I use it to compute spearman's correlation between brain map and surrogate maps

**Comment by jbburt** [comment]
Ahh I totally forgot about the analysis module, sorry! The only reason that I included Pearson correlation was because I had a nice computationally efficient implementation that utilizes vector operations that results in significant speed increases. Unfortunately, as far as I know, is not straightforward to do something analogous for Spearman rank correlation. But you could easily do this analysis yourself using for-loops and the scipy.stats.spearmanr function (which computes the Spearman rank correlation between two one-dimensional vectors).

**Comment by YaoMeng94** [comment]
Understood, thanks for the quick answer, It makes sense to me. Again, appreciate the develop of BrainSMASH, it's a great help!

**Comment by rmarkello** [comment]
@YaoMeng94: If I'm understanding your question correctly, as an alternative to for-loops you can pair `scipy.stats.rankdata` with the implementation of pearsonr in `brainsmash` to compute "efficient" Spearman correlations. You'd first pass your arrays to `scipy.stats.rankdata` (providing the appropriate `axis` parameter to ensure you're calculating ranks separately for each row), the results of which could then be passed directly to `brainsmash.mapgen.stats.pearsonr`.

**Comment by YaoMeng94** [comment]
Great👍🏼! I will give a try, thanks for answering😁

**Comment by jbburt** [comment]
Awesome, I wasn't aware of the `rankdata` function!

**Comment by rmarkello** [comment]
Note that the ranking procedure will still take quite a bit of time (`scipy.stats.rankdata` with the `axis` parameter takes ~approximately as long as running the same function in a for-loop over the rows of the array), but you should definitely see computation benefits from the efficient implementation of `pearsonr` on the resultant ranked arrays over a serial for-loop of `spearmanr`!

**Comment by jbburt** [comment]
I just pushed an update to BrainSMASH which implements this! @YaoMeng94 please let me know if it works for you.

**Comment by YaoMeng94** [comment]
It works quite well ! Very appreciate your quick update and sorry for the late response (Different timezone, Beijing Time) .
