### ISSUE TITLE
Loosen exact dependency requirements

### ISSUE THREAD

**Issue by rmarkello** [murraylab/brainsmash#2]
## Description

Currently all the dependencies for `brainsmash` are pinned in the [requirements.txt](https://github.com/murraylab/brainsmash/blob/205dcf7d7463e3e9d86c62d517ecce014b563248/requirements.txt) file. While this will definitely ensure that users don't have any dependency issues on install, it also makes it difficult to install other packages (that might conflict with these requirements) in the same environment.

## Proposed solution

Would it be possible to consider loosening the package requirements to be e.g., `>=` rather than `==` so that you're only pinning minimum rather than exact dependencies? I see you have a note about known compatibility issues with newer versions of `nibabel`, but beyond that do you foresee issues? (I'd be happy to try and help troubleshoot the `nibabel` issue, if that might help!)

**Comment by rmarkello** [comment]
Sorry, I just saw that you're only pinning the dependencies in the `requirements.txt` and not for the actual install. Still happy to help resolve any `nibabel` compatibility issues to allow for newer versions of that, if needed!

**Comment by jbburt** [comment]
If you're willing to sort out the nibabel incompatibility I would very much appreciate that. I haven't done it because it hasn't been crucial, but you're right in that I shouldn't have this strict of a dependency in a public software package.

**Comment by rmarkello** [comment]
Looks like there's only three occurrences of `nibabel` in the repo, confinded to the following functions:

https://github.com/murraylab/brainsmash/blob/5f86928b58da314c0380b7bcfa84a2351396773d/brainsmash/workbench/io.py#L41-L43

https://github.com/murraylab/brainsmash/blob/5f86928b58da314c0380b7bcfa84a2351396773d/brainsmash/utils/dataio.py#L149-L151

https://github.com/murraylab/brainsmash/blob/5f86928b58da314c0380b7bcfa84a2351396773d/brainsmash/utils/dataio.py#L167-L170

Any memory of which was causing the issue? I have some ideas taking a quick look but figured it'd be worth asking.

**Comment by jbburt** [comment]
I took a look (because I didn't remember) and it actually ended up being something pretty trivial, so I just went ahead and fixed it. Thanks for bringing this up!! (also if you run into any problems with nibabel 3.1.0, please let me know)

**Comment by rmarkello** [comment]
Awesome! Thanks so much :+1: 

Closed with f686bb7.
