### ISSUE TITLE
Questions about the parameter tuning

### ISSUE THREAD

**Issue by younghoo** [murraylab/brainsmash#32]
Hello expert,

When I use BrainSMASH, I would first check the variogram fit visually using the default parameters. If the fit is bad, for instance, the empirical variogram far from the surrogate mean variogram, I would tune the parameters to make the fit acceptable. After choosing the right parameters, the surrogate data are generated for statistical analysis. Do you think my procedure is correct or not? How the goodness of variogram fit will influence the final statistical inference? Is there any standard to check whether the variogram fit is acceptable or not (instead of visual check)? 

Sorry if these questions are answered in the original paper, as the technical details are too difficult for me. 

Many thanks!

**Comment by jbburt** [comment]
Yes, your procedure sounds correct. This is briefly discussed in the [online docs](https://brainsmash.readthedocs.io/en/latest/gettingstarted.html#evaluating-variogram-fits). We didn't develop a mathematically rigorous approach to evaluate variograms' goodness-of-fit... but from prior experience, I can say that when the fit is poor, it is quite obvious (looking at the figure on the page linked to above, you can see almost perfect overlap between the shaded region, representing variance in the surrogate maps variograms, and the open black circles, representing the empirical variogram; when the fit is poor, this will not be the case).
