### ISSUE TITLE
Replace `sklearn` dependency in setup.py with `scikit-learn`

### ISSUE THREAD

**Issue by rmarkello** [murraylab/brainsmash#5]
## Description

I noticed that the `setup.py` file currently lists the following requirements:

https://github.com/murraylab/brainsmash/blob/fda9d3fe9771d368c492faaed1dda675ad67106d/setup.py#L6

Notably, while `scikit-learn` _is_ imported with `import sklearn`, it needs to be installed as `scikit-learn`. (The [`sklearn`](pypi.org/project/sklearn/) package is empty—it exists to prevent malicious actors from capitalizing on the namespace.) Thus, if a user doesn't install `scikit-learn` on their own, trying to import anything from `brainsmash.mapgen` will fail with an ImportError.

## Proposed solution

Simply replacing `sklearn` with `scikit-learn` in the aforementioned line of the setup.py should fix things up!

**Comment by jbburt** [comment]
great catch! I never knew that was why sklearn existed. I'll change this
